### ISSUE TITLE
DatabaseConfigが保存されない

### ISSUE THREAD

**Issue by ryotakato** [adarapata/Natto#14]
はじめまして。

SQLite3で動かそうとしたところ、
DatabaseConfigに、SQLiteファイル名をいれても、
次回の起動時にデフォルトであるSample.dbに戻ってしまいます。

当方、Unity 4.6.3f1を使用しています。
何か設定が必要でしょうか？

**Comment by adarapata** [comment]
@ryotakato 
こちら5.0.1でも再現しました。
4.6時代では変更できたが、それを5系に上げて確認したらファイル名が変更できなくなったのでUnityの内部で仕様が変わったっぽい・・・？
なので現状使えないです・・。

バグ報告ありがとうございます！ :bow:

**Comment by adarapata** [comment]
@ryotakato 
上記不具合修正しました！
報告ありがとうございました。

**Comment by ryotakato** [comment]
対応ありがとうございます！試してみます！
